# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/apex/log"
  version = "1.0.0"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "8.0.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.47"

[[constraint]]
  name = "github.com/cenkalti/backoff"
  version = "1.1.0"

[[constraint]]
  name = "github.com/fatih/structtag"
  version = "0.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/google/go-github"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/knq/snaker"

[[constraint]]
  name = "github.com/mafredri/cdp"
  version = "1.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/matthewmueller/firehose-analytics"

[[constraint]]
  branch = "master"
  name = "github.com/matthewmueller/log"

[[constraint]]
  branch = "master"
  name = "github.com/matthewmueller/store"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  version = "0.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/radovskyb/watcher"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/rapidloop/skv"

[[constraint]]
  name = "github.com/sanity-io/litter"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/sergi/go-diff"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/tj/go-prompt"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[[constraint]]
  branch = "master"
  name = "golang.org/x/tools"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.2.5"
